import Head from 'next/head'

import LoadingPage from '../components/Loading/Loading';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CHAP website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <LoadingPage /> 
      </main>

    </div>
  )
}
