import Head from 'next/head'
import Image from 'next/image'

import Hello from '../components/Hello';
import Icon from '../components/general/TerminalIcon';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div><Icon /></div>

        
        
      </main>

    </div>
  )
}
