import Head from 'next/head'
import SideBarCircles from '../components/General/SideBarCircles';
import ExecsPageHeading from '../components/Layout/ExecsPageHeading'
import Hello from '../components/Home/Hello';

export default function Home() {
  return (
    <div>
      <Head>
        <title>CHAP website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hello /> 
        <SideBarCircles />
        <ExecsPageHeading />
      </main>

    </div>
  )
}
